import Head from "next/head";

const RenderHead = ({ title }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/joe-logo.svg" />
    </Head>
  );
};

export default RenderHead;
